import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "LinkedIn Hook Grader | Myntmore - Free B2B Outreach Tool",
  description: "Audit the first two lines of your LinkedIn post. Get a deterministic score out of 100 and 3 high-converting rewrites generated by AI.",
  openGraph: {
    title: "LinkedIn Hook Grader | Myntmore",
    description: "Audit the first two lines of your LinkedIn post before you publish.",
    url: "https://myntmore.com/tools/linkedin-hook-grader",
    siteName: "Myntmore",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased bg-[#0B0F17] text-[#E2E8F0] min-h-screen">
        {children}
      </body>
    </html>
  );
}
